# Form implementation generated from reading ui file 'add_sale.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddSaleForm(object):
    def setupUi(self, AddSaleForm):
        AddSaleForm.setObjectName("AddSaleForm")
        AddSaleForm.resize(266, 105)
        self.widget = QtWidgets.QWidget(parent=AddSaleForm)
        self.widget.setGeometry(QtCore.QRect(10, 7, 251, 91))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.cleint_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.cleint_combo_box.setObjectName("cleint_combo_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cleint_combo_box)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.car_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.car_combo_box.setObjectName("car_combo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.car_combo_box)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.date_edit = QtWidgets.QDateEdit(parent=self.widget)
        self.date_edit.setObjectName("date_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.date_edit)
        self.add_button = QtWidgets.QPushButton(parent=self.widget)
        self.add_button.setObjectName("add_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.add_button)

        self.retranslateUi(AddSaleForm)
        QtCore.QMetaObject.connectSlotsByName(AddSaleForm)

    def retranslateUi(self, AddSaleForm):
        _translate = QtCore.QCoreApplication.translate
        AddSaleForm.setWindowTitle(_translate("AddSaleForm", "Добавить продажу"))
        self.label.setText(_translate("AddSaleForm", "Клиент:"))
        self.label_2.setText(_translate("AddSaleForm", "Автомобиль:"))
        self.label_3.setText(_translate("AddSaleForm", "Дата продажи:"))
        self.add_button.setText(_translate("AddSaleForm", "Добавить"))
