# Form implementation generated from reading ui file 'edit_client.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditClientForm(object):
    def setupUi(self, EditClientForm):
        EditClientForm.setObjectName("EditClientForm")
        EditClientForm.resize(266, 105)
        self.layoutWidget = QtWidgets.QWidget(parent=EditClientForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 7, 251, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.save_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.save_button)
        self.full_name_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.full_name_line_edit.setObjectName("full_name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.full_name_line_edit)
        self.phone_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.phone_line_edit.setObjectName("phone_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phone_line_edit)
        self.email_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.email_line_edit.setObjectName("email_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.email_line_edit)

        self.retranslateUi(EditClientForm)
        QtCore.QMetaObject.connectSlotsByName(EditClientForm)

    def retranslateUi(self, EditClientForm):
        _translate = QtCore.QCoreApplication.translate
        EditClientForm.setWindowTitle(_translate("EditClientForm", "Редактировать клиента"))
        self.label.setText(_translate("EditClientForm", "ФИО:"))
        self.label_2.setText(_translate("EditClientForm", "Телефон:"))
        self.label_3.setText(_translate("EditClientForm", "Почта:"))
        self.save_button.setText(_translate("EditClientForm", "Сохранить"))
