# Form implementation generated from reading ui file 'edit_car.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditCarForm(object):
    def setupUi(self, EditCarForm):
        EditCarForm.setObjectName("EditCarForm")
        EditCarForm.resize(266, 255)
        self.layoutWidget = QtWidgets.QWidget(parent=EditCarForm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 229, 233))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 8, 1, 1, 1)
        self.transmission_combo_box = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.transmission_combo_box.setObjectName("transmission_combo_box")
        self.gridLayout.addWidget(self.transmission_combo_box, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.vin_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.vin_line_edit.setObjectName("vin_line_edit")
        self.gridLayout.addWidget(self.vin_line_edit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.brand_combo_box = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.brand_combo_box.setObjectName("brand_combo_box")
        self.gridLayout.addWidget(self.brand_combo_box, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.color_combo_box = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.color_combo_box.setObjectName("color_combo_box")
        self.gridLayout.addWidget(self.color_combo_box, 3, 1, 1, 1)
        self.model_combo_box = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.model_combo_box.setObjectName("model_combo_box")
        self.gridLayout.addWidget(self.model_combo_box, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.mileage_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.mileage_line_edit.setObjectName("mileage_line_edit")
        self.gridLayout.addWidget(self.mileage_line_edit, 6, 1, 1, 1)
        self.price_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.price_line_edit.setObjectName("price_line_edit")
        self.gridLayout.addWidget(self.price_line_edit, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.year_line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.year_line_edit.setObjectName("year_line_edit")
        self.gridLayout.addWidget(self.year_line_edit, 5, 1, 1, 1)

        self.retranslateUi(EditCarForm)
        QtCore.QMetaObject.connectSlotsByName(EditCarForm)

    def retranslateUi(self, EditCarForm):
        _translate = QtCore.QCoreApplication.translate
        EditCarForm.setWindowTitle(_translate("EditCarForm", "Редактировать автомобиль"))
        self.save_button.setText(_translate("EditCarForm", "Сохранить"))
        self.label_5.setText(_translate("EditCarForm", "Тип трансмиссии:"))
        self.label_7.setText(_translate("EditCarForm", "Цена:"))
        self.label.setText(_translate("EditCarForm", "VIN:"))
        self.label_3.setText(_translate("EditCarForm", "Модель:"))
        self.label_2.setText(_translate("EditCarForm", "Марка:"))
        self.label_4.setText(_translate("EditCarForm", "Цвет:"))
        self.label_6.setText(_translate("EditCarForm", "Пробег:"))
        self.label_8.setText(_translate("EditCarForm", "Год выпуска:"))
