# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(286, 147)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_line_edit = QtWidgets.QLineEdit(parent=LoginForm)
        self.login_line_edit.setObjectName("login_line_edit")
        self.verticalLayout.addWidget(self.login_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(parent=LoginForm)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.verticalLayout.addWidget(self.password_line_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.login_button = QtWidgets.QPushButton(parent=LoginForm)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Автосалон"))
        self.login_line_edit.setPlaceholderText(_translate("LoginForm", "Логин.."))
        self.password_line_edit.setPlaceholderText(_translate("LoginForm", "Пароль.."))
        self.login_button.setText(_translate("LoginForm", "Войти"))
